using System;
using System.Collections.Generic;
using System.Text;

namespace FitnessApp01.Helpers
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	// If you change the class to 'public' in order to use it outside its assembly
	//  you should also change the fields from 'const' to 'public static readonly'
	static class IconFont
	{
		public const string User = "\uf007";
		public const string AngleLeft = "\uf104";
		public const string AngleRight = "\uf105";
		public const string BookOpen = "\uf518";
		public const string Book = "\uf02d";
		public const string ClipboardList = "\uf46d";
		public const string Trash = "\uf1f8";
		public const string Plus = "\uf067";
		public const string Cog = "\uf013";
	}
}
