//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApp01.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessApp01.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název výrobce (volitelné).
        /// </summary>
        public static string AddFoodPage_Brand {
            get {
                return ResourceManager.GetString("AddFoodPage_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacharidy.
        /// </summary>
        public static string AddFoodPage_Carbs {
            get {
                return ResourceManager.GetString("AddFoodPage_Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energetická hodnota.
        /// </summary>
        public static string AddFoodPage_Energy {
            get {
                return ResourceManager.GetString("AddFoodPage_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuky.
        /// </summary>
        public static string AddFoodPage_Fats {
            get {
                return ResourceManager.GetString("AddFoodPage_Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vláknina (volitelné).
        /// </summary>
        public static string AddFoodPage_Fiber {
            get {
                return ResourceManager.GetString("AddFoodPage_Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výživové údaje na.
        /// </summary>
        public static string AddFoodPage_Nutritions {
            get {
                return ResourceManager.GetString("AddFoodPage_Nutritions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím, zkontrolujte, zda máte vyplněné všechny povinné údaje a zda nepoužíváte znaky &amp; a #.
        /// </summary>
        public static string AddFoodPage_PleaseCheckInputs {
            get {
                return ResourceManager.GetString("AddFoodPage_PleaseCheckInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velikost balení/porce (volitelné).
        /// </summary>
        public static string AddFoodPage_Portion {
            get {
                return ResourceManager.GetString("AddFoodPage_Portion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bílkoviny.
        /// </summary>
        public static string AddFoodPage_Protein {
            get {
                return ResourceManager.GetString("AddFoodPage_Protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sůl (volitelné).
        /// </summary>
        public static string AddFoodPage_Salt {
            get {
                return ResourceManager.GetString("AddFoodPage_Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z toho nasycené mastné kyseliny (volitelné).
        /// </summary>
        public static string AddFoodPage_SaturatedFats {
            get {
                return ResourceManager.GetString("AddFoodPage_SaturatedFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z toho cukry.
        /// </summary>
        public static string AddFoodPage_Sugar {
            get {
                return ResourceManager.GetString("AddFoodPage_Sugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tvorba nové potraviny.
        /// </summary>
        public static string AddFoodPageTitle {
            get {
                return ResourceManager.GetString("AddFoodPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Věk.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatné údaje..
        /// </summary>
        public static string BadCredentials {
            get {
                return ResourceManager.GetString("BadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snídaně.
        /// </summary>
        public static string Breakfast {
            get {
                return ResourceManager.GetString("Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijato:.
        /// </summary>
        public static string CaloriesCurrent {
            get {
                return ResourceManager.GetString("CaloriesCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánovaný příjem energie:.
        /// </summary>
        public static string CaloriesGoal {
            get {
                return ResourceManager.GetString("CaloriesGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze uložit. Musíte vyplnit potřebné údaje..
        /// </summary>
        public static string CanNotSave {
            get {
                return ResourceManager.GetString("CanNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit úroveň aktivity.
        /// </summary>
        public static string ChangeActivity {
            get {
                return ResourceManager.GetString("ChangeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit věk.
        /// </summary>
        public static string ChangeAge {
            get {
                return ResourceManager.GetString("ChangeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit denní přijem energie.
        /// </summary>
        public static string ChangeCaloriesGoal {
            get {
                return ResourceManager.GetString("ChangeCaloriesGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit emailovou adresu.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit cíl.
        /// </summary>
        public static string ChangeGoal {
            get {
                return ResourceManager.GetString("ChangeGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit výšku.
        /// </summary>
        public static string ChangeHeight {
            get {
                return ResourceManager.GetString("ChangeHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit makra.
        /// </summary>
        public static string ChangeMacros {
            get {
                return ResourceManager.GetString("ChangeMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit heslo.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit rychlost dosažení cíle (nedoporučuje se).
        /// </summary>
        public static string ChangeSpeed {
            get {
                return ResourceManager.GetString("ChangeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změnit cílovou váhu.
        /// </summary>
        public static string ChangeWeight {
            get {
                return ResourceManager.GetString("ChangeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zkontrolujte svou emailovou schránku..
        /// </summary>
        public static string CheckEmail {
            get {
                return ResourceManager.GetString("CheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diář.
        /// </summary>
        public static string Diary {
            get {
                return ResourceManager.GetString("Diary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Večeře.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava záznamu.
        /// </summary>
        public static string EditMeal {
            get {
                return ResourceManager.GetString("EditMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žena.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyhledat potravinu....
        /// </summary>
        public static string FindFood {
            get {
                return ResourceManager.GetString("FindFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název potraviny.
        /// </summary>
        public static string FoodName {
            get {
                return ResourceManager.GetString("FoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výška.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vláknina.
        /// </summary>
        public static string HomePage_Fiber {
            get {
                return ResourceManager.GetString("HomePage_Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sůl.
        /// </summary>
        public static string HomePage_Salt {
            get {
                return ResourceManager.GetString("HomePage_Salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasycené mastné kyseliny.
        /// </summary>
        public static string HomePage_SaturatedFats {
            get {
                return ResourceManager.GetString("HomePage_SaturatedFats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Připojení k internetu je dostupné..
        /// </summary>
        public static string InternetAvailable {
            get {
                return ResourceManager.GetString("InternetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se připojit k internetu. Zkontrolujte nastavení internetu a zkuste to znovu..
        /// </summary>
        public static string InternetRequired {
            get {
                return ResourceManager.GetString("InternetRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailová adresa je neplatná..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neexistující uživatel..
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již máte účet?.
        /// </summary>
        public static string LoginPage_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("LoginPage_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginPage_EmailPlaceHolder {
            get {
                return ResourceManager.GetString("LoginPage_EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomenuté heslo?.
        /// </summary>
        public static string LoginPage_ForgotPassword {
            get {
                return ResourceManager.GetString("LoginPage_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string LoginPage_Login {
            get {
                return ResourceManager.GetString("LoginPage_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se.
        /// </summary>
        public static string LoginPage_LoginButton {
            get {
                return ResourceManager.GetString("LoginPage_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte účet?.
        /// </summary>
        public static string LoginPage_NoAccount {
            get {
                return ResourceManager.GetString("LoginPage_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musíte vyplnit emailovou adresu a heslo..
        /// </summary>
        public static string LoginPage_NoEmailOrPassword {
            get {
                return ResourceManager.GetString("LoginPage_NoEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo znovu.
        /// </summary>
        public static string LoginPage_PasswordConfirmPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordConfirmPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string LoginPage_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obnovit heslo.
        /// </summary>
        public static string LoginPage_PasswordReset {
            get {
                return ResourceManager.GetString("LoginPage_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat.
        /// </summary>
        public static string LoginPage_Register {
            get {
                return ResourceManager.GetString("LoginPage_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrovat se.
        /// </summary>
        public static string LoginPage_RegisterButton {
            get {
                return ResourceManager.GetString("LoginPage_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oběd.
        /// </summary>
        public static string Lunch {
            get {
                return ResourceManager.GetString("Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna poměru makroživin.
        /// </summary>
        public static string MacrosChangePage {
            get {
                return ResourceManager.GetString("MacrosChangePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muž.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo znovu.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není co uložit..
        /// </summary>
        public static string NothingToSave {
            get {
                return ResourceManager.GetString("NothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staré heslo.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přehled.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesla se neshodují..
        /// </summary>
        public static string PasswordConfirmError {
            get {
                return ResourceManager.GetString("PasswordConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo musí být jiné než staré heslo..
        /// </summary>
        public static string PasswordNotDifferent {
            get {
                return ResourceManager.GetString("PasswordNotDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zadejte email vašeho účtu: .
        /// </summary>
        public static string PasswordResetPage_email {
            get {
                return ResourceManager.GetString("PasswordResetPage_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odeslat.
        /// </summary>
        public static string PasswordResetPage_send {
            get {
                return ResourceManager.GetString("PasswordResetPage_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předchozí.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neočekávaná chyba během ověřování uživatele..
        /// </summary>
        public static string Reauthenticate_UnexpectedError {
            get {
                return ResourceManager.GetString("Reauthenticate_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nepodařilo se aktualizovat registrační údaje..
        /// </summary>
        public static string RegSettingsUpdateError {
            get {
                return ResourceManager.GetString("RegSettingsUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaslání emailu pro obnovu hesla.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problém při odesílání resetovacího emailu.
        /// </summary>
        public static string ResetPasswordError {
            get {
                return ResourceManager.GetString("ResetPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit změny.
        /// </summary>
        public static string SaveChanged {
            get {
                return ResourceManager.GetString("SaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Všechny provedené změny je potřeba uložit. V opačném případě budou při dalším spuštění aplikace vráceny do původního stavu..
        /// </summary>
        public static string SaveChangedWarning {
            get {
                return ResourceManager.GetString("SaveChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Výběr potraviny.
        /// </summary>
        public static string SelectMealPageTitle {
            get {
                return ResourceManager.GetString("SelectMealPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna nastavení.
        /// </summary>
        public static string SettingsChange {
            get {
                return ResourceManager.GetString("SettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit se.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba při odhlašování.
        /// </summary>
        public static string SignOutError {
            get {
                return ResourceManager.GetString("SignOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svačina.
        /// </summary>
        public static string Snack {
            get {
                return ResourceManager.GetString("Snack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Začít.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podařilo se.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámá chyba. Zkontrolujte připojení k internetu..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vámi zadaný uživatel již existuje..
        /// </summary>
        public static string UserCollision {
            get {
                return ResourceManager.GetString("UserCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vámi zadané heslo je příliš slabé (heslo by mělo mít alespoň 6 znaků).
        /// </summary>
        public static string WeakPasswordException {
            get {
                return ResourceManager.GetString("WeakPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váha.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vítejte.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyní Vás aplikace provede základním nastavením..
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úrověň fyzické aktivity.
        /// </summary>
        public static string YourActivity {
            get {
                return ResourceManager.GetString("YourActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš věk:.
        /// </summary>
        public static string YourAge {
            get {
                return ResourceManager.GetString("YourAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaká je Vaše vysněná váha?.
        /// </summary>
        public static string YourDesiredWeight {
            get {
                return ResourceManager.GetString("YourDesiredWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše pohlaví:.
        /// </summary>
        public static string YourGender {
            get {
                return ResourceManager.GetString("YourGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaký je Váš cíl?.
        /// </summary>
        public static string YourGoal {
            get {
                return ResourceManager.GetString("YourGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše výška:.
        /// </summary>
        public static string YourHeight {
            get {
                return ResourceManager.GetString("YourHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaše váha:.
        /// </summary>
        public static string YourWeight {
            get {
                return ResourceManager.GetString("YourWeight", resourceCulture);
            }
        }
    }
}
